version: "3.8"

services:
  backend:
    image: 856563400605.dkr.ecr.us-east-1.amazonaws.com/huggingface-backend:latest
    container_name: huggingface-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    image: 856563400605.dkr.ecr.us-east-1.amazonaws.com/huggingface-frontend:latest
    container_name: huggingface-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:5000/generate
    depends_on:
      - backend
    restart: always
