version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: huggingface-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: huggingface-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:5000/generate
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
